<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by prose ;-) -->
<!--   Remove << >>;   -->
<!--   Replace "urn-to-be-replaced" by "http://www.w3.org/1999/XSL/Transform"; and -->
<!--   Save as "generated.formatA-to-formatB.xsl" -->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<xsl:output method="xml" encoding="UTF-8" indent="yes" />
<xsl:template match="/Toto">
<xsl:comment>
<xsl:text> Save as </xsl:text>
<xsl:text>"</xsl:text>
<xsl:text>formatB</xsl:text>
<xsl:text>.instance.mapped-from-</xsl:text>
<xsl:text>formatA</xsl:text>
<xsl:text>.xml" </xsl:text>
</xsl:comment>
<xsl:element name="toto" />
</xsl:template>
</xsl:stylesheet>
